configfile: "../config/config.yml"

import os
from pathlib import Path
from dotenv import load_dotenv
env_file = Path("../.env").resolve()
load_dotenv(str(env_file))

envvars:
    "ISONE_USERNAME",
    "ISONE_PASSWORD"

DATA_DIR = Path("../data/")

rule retrieve_isone_load:
    params:
        username = os.environ['ISONE_USERNAME'],
        password = os.environ['ISONE_PASSWORD']
    output: 
        demand_data = DATA_DIR/f"isone_load_{config['start_date']}_{config['end_date']}.csv"
    script: 
        "scripts/retrieve_isone_rt_demand.py"

rule retrieve_era5:
    output:
        archive = DATA_DIR/"era5_download.zip"
    script:
        "scripts/retrieve_era5.py"

rule extract_era5:
    input:
        archive = DATA_DIR/"era5_download.zip"
    output:
        era5 = DATA_DIR/f"{config['dataset_id']}_{config['start_date']}_{config['end_date']}.csv"
    run:
        import zipfile
        import shutil

        with zipfile.ZipFile(input.archive, 'r') as zf:
            for member in zf.namelist():
                if (config['dataset_id'] in member) & ('csv' in member):
                    source = zf.open(member)

                    target = open(output.era5, 'wb')
                    with source, target:
                        shutil.copyfileobj(source, target)
                else:
                    print(f'Skipping {member}')