name: osw
channels:
    - conda-forge
    - bioconda
    - nodefaults
dependencies:
    # Requirements for core model functionality
    - python == 3.13.14
    - pip
    - ipython
    - jupyterlab
    - matplotlib
    - pandas
    - numpy
    - scipy
    - ipykernel
    - pyarrow
    - xarray
    - dask
    - netCDF4
    - eccodes
    - bottleneck
    - snakemake-minimal
    - atlite
    - pip:
      - cfgrib
      - cdsapi
      - tqdm
      - python-dotenv